def generate_training_code(model_info: dict) -> str:
    """
    Generates a ready-to-use Python training script.
    ✅  Now uses sklearn Pipeline -> no data leakage.
    Uses model_info dict returned by select_best_model().
    """

    model_name   = model_info['best_name']
    problem_type = model_info['problem_type']
    target_name  = model_info.get('target_name', 'target')

    # ── Header ──────────────────────────────────────────────────
    code = f'''# Auto-generated by AutoML Copilot
# Best model selected : {model_name}
# Problem type        : {problem_type}
# ✅ Uses Pipeline — no data leakage

import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_selection import SelectKBest, f_classif, f_regression
from sklearn.impute import SimpleImputer

'''

    # ── Model-specific import ────────────────────────────────────
    if 'Neural Network' in model_name:
        if problem_type == 'classification':
            code += 'from sklearn.neural_network import MLPClassifier\n\n'
        else:
            code += 'from sklearn.neural_network import MLPRegressor\n\n'
    elif 'Random Forest' in model_name:
        if problem_type == 'classification':
            code += 'from sklearn.ensemble import RandomForestClassifier\n\n'
        else:
            code += 'from sklearn.ensemble import RandomForestRegressor\n\n'
    elif model_name == 'Logistic Regression':
        code += 'from sklearn.linear_model import LogisticRegression\n\n'
    elif model_name == 'Linear Regression':
        code += 'from sklearn.linear_model import LinearRegression\n\n'
    elif model_name == 'SVM':
        if problem_type == 'classification':
            code += 'from sklearn.svm import SVC\n\n'
        else:
            code += 'from sklearn.svm import SVR\n\n'
    elif model_name == 'XGBoost':
        if problem_type == 'classification':
            code += 'from xgboost import XGBClassifier\n\n'
        else:
            code += 'from xgboost import XGBRegressor\n\n'

    # ── Step 1: Load ────────────────────────────────────────────
    code += f'''# ── Step 1: Load data ──────────────────────────────────────────
df = pd.read_csv("your_dataset.csv")

'''

    # ── Step 2: Preprocessing ───────────────────────────────────
    code += f'''# ── Step 2: Basic preprocessing ────────────────────────────────
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype in ["int64", "float64"]:
            imputer = SimpleImputer(strategy="mean")
        else:
            imputer = SimpleImputer(strategy="most_frequent")
        df[col] = imputer.fit_transform(df[[col]]).ravel()

for col in df.select_dtypes(include=["object"]).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

X = df.drop(columns=["{target_name}"])
y = df["{target_name}"]

# ✅ Split BEFORE any scaling/selection (Pipeline handles the rest)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

'''

    # ── Step 3: Pipeline ────────────────────────────────────────
    score_fn = 'f_classif' if problem_type == 'classification' else 'f_regression'

    code += f'''# ── Step 3: Build Pipeline (scaling + selection + model) ────────
# ✅ Preprocessing runs INSIDE the pipeline -> no leakage during CV
'''

    if 'Neural Network' in model_name:
        estimator_str = (
            'MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)'
            if problem_type == 'classification' else
            'MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)'
        )
    elif 'Random Forest' in model_name:
        estimator_str = (
            'RandomForestClassifier(n_estimators=100, random_state=42)'
            if problem_type == 'classification' else
            'RandomForestRegressor(n_estimators=100, random_state=42)'
        )
    elif model_name == 'Logistic Regression':
        estimator_str = 'LogisticRegression(max_iter=1000, random_state=42)'
    elif model_name == 'Linear Regression':
        estimator_str = 'LinearRegression()'
    elif model_name == 'SVM':
        estimator_str = (
            'SVC(kernel="rbf", random_state=42)'
            if problem_type == 'classification' else
            'SVR(kernel="rbf")'
        )
    elif model_name == 'XGBoost':
        estimator_str = (
            'XGBClassifier(n_estimators=100, random_state=42, eval_metric="logloss")'
            if problem_type == 'classification' else
            'XGBRegressor(n_estimators=100, random_state=42)'
        )
    else:
        estimator_str = '# TODO: add your estimator here'

    code += f'''
model = Pipeline([
    ("scaler",   StandardScaler()),
    ("selector", SelectKBest(score_func={score_fn}, k="all")),
    ("model",    {estimator_str}),
])

# Optional: verify with cross-validation (runs on training data only)
scoring = "{'accuracy' if problem_type == 'classification' else 'neg_mean_squared_error'}"
cv_scores = cross_val_score(model, X_train, y_train, cv=5, scoring=scoring)
print(f"CV scores : {{cv_scores}}")
print(f"CV mean   : {{cv_scores.mean():.4f}}")

'''

    # ── Step 4: Fit + evaluate ──────────────────────────────────
    code += '''# ── Step 4: Final training ─────────────────────────────────────
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

'''

    if problem_type == 'classification':
        code += '''# ── Step 5: Evaluation ─────────────────────────────────────────
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)

print(f"Accuracy : {accuracy_score(y_test, y_pred):.4f}")
print(classification_report(y_test, y_pred))

# Confusion matrix chart
cm   = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(6, 5))
disp.plot(ax=ax, colorbar=False, cmap="Blues")
ax.set_title("Confusion Matrix")
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()
print("Chart saved: confusion_matrix.png")
'''
    else:
        code += '''# ── Step 5: Evaluation ─────────────────────────────────────────
from sklearn.metrics import mean_squared_error, r2_score

print(f"MSE : {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2  : {r2_score(y_test, y_pred):.4f}")
'''

    return code


# ============================================================
# Quick test
# ============================================================
if __name__ == "__main__":
    for model_name in [
        'Neural Network (MLP)', 'Random Forest',
        'Logistic Regression', 'SVM', 'XGBoost'
    ]:
        mock_info = {
            'best_name':    model_name,
            'problem_type': 'classification',
            'target_name':  'target',
        }
        code = generate_training_code(mock_info)
        assert '{}' not in code, f"ERROR: empty braces in output for {model_name}"
        assert 'Pipeline' in code, "ERROR: Pipeline missing from generated code!"
        print(f"✅  {model_name} — code generated OK")

    print("\n--- code_generator tests passed ---")