def generate_training_code(model_info: dict) -> str:
    """
    Generates a ready-to-use Python training script based on the best model found.
    Uses model_info dict returned by select_best_model().
    """

    model_name   = model_info['best_name']
    problem_type = model_info['problem_type']
    target_name  = model_info.get('target_name', 'target')

    # ============================================================
    # Header + imports
    # ============================================================
    code = f'''# Auto-generated by Data Science Copilot
# Best model selected: {model_name}
# Problem type: {problem_type}

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_selection import SelectKBest, f_classif, f_regression
from sklearn.impute import SimpleImputer

'''

    # ============================================================
    # Model-specific import
    # ============================================================
    if 'Neural Network' in model_name:
        if problem_type == 'classification':
            code += 'from sklearn.neural_network import MLPClassifier\n\n'
        else:
            code += 'from sklearn.neural_network import MLPRegressor\n\n'
    elif model_name == 'Random Forest':
        if problem_type == 'classification':
            code += 'from sklearn.ensemble import RandomForestClassifier\n\n'
        else:
            code += 'from sklearn.ensemble import RandomForestRegressor\n\n'
    elif model_name == 'Logistic Regression':
        code += 'from sklearn.linear_model import LogisticRegression\n\n'
    elif model_name == 'Linear Regression':
        code += 'from sklearn.linear_model import LinearRegression\n\n'

    # ============================================================
    # Step 1: Data loading
    # ============================================================
    code += f'''# ── Step 1: Load data ──────────────────────────────────────────
df = pd.read_csv("your_dataset.csv")

'''

    # ============================================================
    # Step 2: Preprocessing
    # Note: use {{}} to output literal braces inside an f-string
    # ============================================================
    code += f'''# ── Step 2: Preprocessing ──────────────────────────────────────
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype in ["int64", "float64"]:
            imputer = SimpleImputer(strategy="mean")
        else:
            imputer = SimpleImputer(strategy="most_frequent")
        df[col] = imputer.fit_transform(df[[col]]).ravel()

# Label encoding for categorical columns
for col in df.select_dtypes(include=["object"]).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

X = df.drop(columns=["{target_name}"])
y = df["{target_name}"]

'''

    # ============================================================
    # Step 3: Feature engineering
    # ============================================================
    score_fn = 'f_classif' if problem_type == 'classification' else 'f_regression'
    code += f'''# ── Step 3: Feature Engineering ────────────────────────────────
scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X)

selector   = SelectKBest(score_func={score_fn}, k="all")
X_selected = selector.fit_transform(X_scaled, y)

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.2, random_state=42
)

'''

    # ============================================================
    # Step 4: Model definition
    # ============================================================
    code += '# ── Step 4: Model ─────────────────────────────────────────────\n'

    if 'Neural Network' in model_name:
        if problem_type == 'classification':
            code += 'model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)\n\n'
        else:
            code += 'model = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)\n\n'
    elif model_name == 'Random Forest':
        if problem_type == 'classification':
            code += 'model = RandomForestClassifier(n_estimators=100, random_state=42)\n\n'
        else:
            code += 'model = RandomForestRegressor(n_estimators=100, random_state=42)\n\n'
    elif model_name == 'Logistic Regression':
        code += 'model = LogisticRegression(max_iter=1000, random_state=42)\n\n'
    elif model_name == 'Linear Regression':
        code += 'model = LinearRegression()\n\n'

    # ============================================================
    # Step 5: Training + evaluation
    # ============================================================
    code += '''# ── Step 5: Training ───────────────────────────────────────────
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

'''

    if problem_type == 'classification':
        code += '''# ── Step 6: Evaluation ─────────────────────────────────────────
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
'''
    else:
        code += '''# ── Step 6: Evaluation ─────────────────────────────────────────
from sklearn.metrics import mean_squared_error, r2_score

print(f"MSE : {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2  : {r2_score(y_test, y_pred):.4f}")
'''

    return code


# ============================================================
# Quick test
# ============================================================
if __name__ == "__main__":
    mock_info = {
        'best_name':    'Neural Network (MLP)',
        'problem_type': 'classification',
        'target_name':  'target',
    }

    code = generate_training_code(mock_info)
    print(code)

    # Verify no unintended blank braces in output
    assert '{}' not in code, "ERROR: empty braces found in generated code!"
    print("--- code_generator test passed ---")